version: 1

project_name: clix
release:
  github:
    owner: clix-so
    name: homebrew-clix-cli
builds:
  - id: clix
    main: main.go
    binary: clix
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

brews:
  - name: clix
    commit_author:
      name: github-actions[bot]
      email: github-actions[bot]@users.noreply.github.com
    homepage: "https://github.com/clix-so/clix-cli"
    description: "A CLI tool for ..."
    test: |
      system "#{bin}/clix", "--version"
    install: |
      bin.install "clix"

    dependencies: []
    caveats: |
      To get started, run:
        clix --help
    # GoReleaser가 자동으로 URL, SHA256, 버전 갱신
