# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clix < Formula
  desc "A CLI tool for ..."
  homepage "https://github.com/clix-so/homebrew-clix-cli"
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/clix-so/homebrew-clix-cli/releases/download/v0.2.3/clix_0.2.3_darwin_amd64.tar.gz"
      sha256 "bfae969599d1d4838724b4c6a0da0933c83e066cd7f316cd46d6bb0f30d629d4"

      def install
        bin.install "clix"
      end
    end
    on_arm do
      url "https://github.com/clix-so/homebrew-clix-cli/releases/download/v0.2.3/clix_0.2.3_darwin_arm64.tar.gz"
      sha256 "567ed58901e1f23c356378fd1a747b7c361b0ff94508d8600ebc42c632a67c93"

      def install
        bin.install "clix"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clix-so/homebrew-clix-cli/releases/download/v0.2.3/clix_0.2.3_linux_amd64.tar.gz"
        sha256 "ff801d75397666b70ab815021851004f082acbadbbe97f65688c15fb6a6184db"

        def install
          bin.install "clix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clix-so/homebrew-clix-cli/releases/download/v0.2.3/clix_0.2.3_linux_arm64.tar.gz"
        sha256 "a6cd208eed190e7a2f84a8bae2738f896e0d11cdc60c73bcb76eeb8130e6ad83"

        def install
          bin.install "clix"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        clix --help
    EOS
  end

  test do
    system "#{bin}/clix", "--version"
  end
end
