# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clix < Formula
  desc "A CLI tool for ..."
  homepage "https://github.com/clix-so/homebrew-clix-cli"
  version "0.2.7"

  on_macos do
    on_intel do
      url "https://github.com/clix-so/homebrew-clix-cli/releases/download/v0.2.7/clix_0.2.7_darwin_amd64.tar.gz"
      sha256 "561f2b276009c6ee5d1058d8bc171079b3510ba88300ceccc03ec13c2ca6c7ea"

      def install
        bin.install "clix"
      end
    end
    on_arm do
      url "https://github.com/clix-so/homebrew-clix-cli/releases/download/v0.2.7/clix_0.2.7_darwin_arm64.tar.gz"
      sha256 "a9a0bebc36a2edd34a83d1ef8c340362599ba88b4332acee3aa5c687f9c8d14a"

      def install
        bin.install "clix"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clix-so/homebrew-clix-cli/releases/download/v0.2.7/clix_0.2.7_linux_amd64.tar.gz"
        sha256 "1451308793197dd80f96bf0220438652104ff5231f9259cc93cac073e5a920bc"

        def install
          bin.install "clix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clix-so/homebrew-clix-cli/releases/download/v0.2.7/clix_0.2.7_linux_arm64.tar.gz"
        sha256 "ccb406c87413ef5ecc620548ba6d6247ccfd973b2a4518f00600180c3041ef28"

        def install
          bin.install "clix"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        clix --help
    EOS
  end

  test do
    system "#{bin}/clix", "--version"
  end
end
